loadstring(game:HttpGet("https://raw.githubusercontent.com/xqrto/Roblox-ZentroHub/main/ZentroHub.lua?nocache="..os.time()))()
loadstring(game:HttpGet("https://raw.githubusercontent.com/xqrto/Roblox-ZentroHub/refs/heads/main/Dbug/Chat.lua"))()
loadstring(game:HttpGet("https://raw.githubusercontent.com/xqrto/Roblox-ZentroHub/refs/heads/main/ZentroUserList.lua"))()
loadstring(game:HttpGet("https://raw.githubusercontent.com/xqrto/Roblox-ZentroHub/refs/heads/main/Intro.lua"))()
loadstring(game:HttpGet("https://raw.githubusercontent.com/xqrto/Roblox-ZentroHub/refs/heads/main/Info.lua"))()
loadstring(game:HttpGet("https://raw.githubusercontent.com/xqrto/Roblox-ZentroHub/refs/heads/main/command.lua"))()